get http://localhost:8080/

###
get http://localhost:8080/api/languages

###
get http://localhost:8080/api/languages/4

###
delete http://localhost:8080/api/languages/3

###
post http://localhost:8080/api/languages/
content-type: application/json

{ "english": "cat", "finnish": "kissa" }